fix crash in log
logger would through the exception
  UnicodeEncodeError: 'ascii' codec can't encode character '\uXXXX' in position 0: ordinal not in range 128
and break the execution pipeline with that because an unicode character was used (e.g. BLACK STAR - U+2605)